name: Deploy production
on: 
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        # Thats is workarround for github actions :(
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env &&
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> .env &&
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env &&
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env &&
          echo "PORT=${{ secrets.PORT }}" >> .env &&
          echo "API_START_ARG=${{ secrets.API_START_ARG }}" >> .env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./k8s/Dockerfile
          push: true
          tags: henricker/pokemon-api:latest
